### ISSUE TITLE
Stream will not load, only shows notifications of deleted tweets.

### ISSUE THREAD

**Issue by BlitzKraft** [DarkDefender/weetweet#13]
This is the sequence of error messages:
```
18:02 =!= | python: error in function "twitter_stream_cb"
18:05     | python: stdout/stderr: Traceback (most recent call last):
18:05     | python: stdout/stderr:   File "/home/bk/.weechat/python/autoload/weetweet.py", line 362, in twitter_stream_cb
18:05     | python: stdout/stderr:     print_tweet_data(buffer,tweet,"id")
18:05     | python: stdout/stderr:   File "/home/bk/.weechat/python/autoload/weetweet.py", line 245, in print_tweet_data
18:05     | python: stdout/stderr:     parse_for_nicks(text,buffer)
18:05     | python: stdout/stderr:   File "/home/bk/.weechat/python/autoload/weetweet.py", line 233, in parse_for_nicks
18:05     | python: stdout/stderr:     match = re.search(regex,word)
18:05     | python: stdout/stderr:   File "/usr/lib64/python3.4/re.py", line 170, in search
18:05     | python: stdout/stderr:     return _compile(pattern, flags).search(string)
18:05     | python: stdout/stderr: TypeError: can't use a string pattern on a bytes-like object
```
This is all I see in the twitter buffer:

```
│-- Thu, 22 Jun 2017 --                                                               │ friends_list
│00:46 -- | Got request to delete: <c0>                                               │ friends_list
│07:29 -- | Got request to delete: <c1>                                               │ friends_list
│08:01 -- | Got request to delete: <c2>                                               │ friends_list
│08:17 -- | Got request to delete: <c3>                                               │ friends_list
│08:20 -- | Got request to delete: <c4>                                               │ friends_list
│13:04 -- | Got request to delete: <c5>                                               │ friends_list
│13:09 -- | Got request to delete: <c6>                                               │ friends_list
```

Not exactly sure what's causing the errors. 

EDIT: My error. I thought I was using the latest version of weetweet. Just check it against master, and I was wrong. Updating it fixed the error.

**Comment by DarkDefender** [comment]
You were not using the weetweet version from the weechat script repo, right? That one should be the same as the current master version.

**Comment by BlitzKraft** [comment]
I forked the repo a long time ago and was using the master that's ~1 year old. I git-fetched the upstream but didn't merge it into my fork. That was the root of the issue. 

I merged it and that worked. Just didn't realize that until it was too late.

**Comment by DarkDefender** [comment]
Ah, ok. Thanks for the clarification! I was worried that something might had broken the script repo version.
