### ISSUE TITLE
Can't :auth

### ISSUE THREAD

**Issue by pztrn** [DarkDefender/weetweet#27]
Trying to authenticate on Twitter using version from /script and got this output:

```
15:43 python: stdout/stderr (weetweet): Traceback (most recent call last):
15:43 python: stdout/stderr (weetweet):   File "/home/pztrn/.weechat/python/weetweet.py", line 1314, in oauth_proc_cb
15:43 python: stdout/stderr (weetweet):     oauth_token, oauth_token_secret = parse_oauth_tokens(out)
15:43 python: stdout/stderr (weetweet):   File "/home/pztrn/.weechat/python/weetweet.py", line 1270, in parse_oauth_tokens
15:43 python: stdout/stderr (weetweet):     return oauth_token, oauth_token_secret
15:43 python: stdout/stderr (weetweet): UnboundLocalError: local variable 'oauth_token' referenced before assignment
```

I'm on Arch Linux, Weechat 2.3, python2 plugin.

**Comment by pztrn** [comment]
Found a reason - python-twitter library should be installed for **both** python2 and python3, because Weechat loads it as python2 script, yet weetweet withing itself executes python3 commands.
